# Generated by Django 5.2 on 2025-11-29 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_availabletimeslot_psychologist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('processing', 'Isleniyor'), ('completed', 'Tamamlandi'), ('failed', 'Basarisiz'), ('cancelled', 'Iptal Edildi'), ('refunded', 'Iade Edildi')], default='pending', max_length=20)),
                ('iyzico_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('iyzico_conversation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('iyzico_basket_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Odeme',
                'verbose_name_plural': 'Odemeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
