# Generated by Django 5.2 on 2025-11-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age_range',
            field=models.CharField(blank=True, choices=[('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-55', '46-55'), ('56-65', '56-65'), ('65+', '65+')], help_text='Yaş aralığı (İçini Dök anketinden)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('kadın', 'Kadın'), ('erkek', 'Erkek'), ('diğer', 'Diğer'), ('belirtmek_istemiyorum', 'Belirtmek İstemiyorum')], help_text='Cinsiyet (İçini Dök anketinden)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('bekar', 'Bekar'), ('evli', 'Evli'), ('boşanmış', 'Boşanmış'), ('dul', 'Dul'), ('nişanlı', 'Nişanlı'), ('birlikte_yaşama', 'Birlikte Yaşama'), ('belirtmek_istemiyorum', 'Belirtmek İstemiyorum')], help_text='Medeni hal (İçini Dök anketinden)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number_of_children',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Çocuk sayısı (İçini Dök anketinden)', null=True),
        ),
    ]
