# Generated by Django 5.2 on 2025-11-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointmentprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Odeme Bekleniyor'), ('paid', 'Odendi'), ('cancelled', 'Iptal Edildi')], default='pending_payment', help_text='Randevu durumu', max_length=20),
        ),
    ]
